# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies and build
COPY package.json pnpm-lock.yaml tsconfig.json ./
# Install the packageManager version declared in package.json via Corepack
RUN corepack enable
RUN pnpm install --frozen-lockfile
COPY src ./src
RUN pnpm build

# Production image
FROM node:lts-alpine
WORKDIR /app
# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# Install locked production dependencies
COPY package.json pnpm-lock.yaml ./
RUN corepack enable
RUN pnpm install --prod --frozen-lockfile
COPY --from=builder /app/build ./build
USER appuser
# Now start the server via stdio transport
ENTRYPOINT ["node","build/index.js"]
