# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies and build
COPY package.json tsconfig.json ./
# Install the packageManager version declared in package.json via Corepack
RUN corepack enable
RUN pnpm install --no-frozen-lockfile
COPY src ./src
RUN pnpm build

# Production image
FROM node:lts-alpine
WORKDIR /app
# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# Copy built files and package.json to install production deps
COPY package.json ./
# Install production dependencies
RUN npm install --production
COPY --from=builder /app/build ./build
USER appuser
# Now start the server via stdio transport
ENTRYPOINT ["node","build/index.js"]
